### ISSUE TITLE
[Question] - On Windows 10 \VOLUME{%IDENTIFIER%}

### ISSUE THREAD

**Issue by hadar0x** [libyal/libagdb#2]
Hi @joachimmetz 

First, it's an opportunity to thank you for all your amazing work, so thanks a lot!

I had a look at the Windows 10 \VOLUME{%IDENTIFIER%}, and it seems that the 2nd part of the identifier is the volume's serial number, e.g.
`5e6d77ca`
is actually the serial number of the volume under C:\, and the process was executed from 
`\VOLUME{01d15f816d07ba5e-5e6d77ca}\Windows\System32`

My question is, do you have any idea what does the first part represent? in my example it's:
`01d15f816d07ba5e`

**Comment by joachimmetz** [comment]
> My question is, do you have any idea what does the first part represent? in my example it's:
01d15f816d07ba5e

based on this single sample this looks like a [FILETIME](https://github.com/log2timeline/dfdatetime/wiki/Date-and-time-values#filetime) 64-bit timestamp:
`datetime.datetime(1601, 1, 1) + datetime.timedelta(microseconds=0x01d15f816d07ba5e/10)`
`datetime.datetime(2016, 2, 4, 19, 22, 45, 509795)`

A guess would be that this maybe is the volume creation time.

**Comment by hadar0x** [comment]
Nice! I verified it, even created new volumes and it does correspond to the volume creation time (in UTC).

Thanks a lot.

**Comment by joachimmetz** [comment]
Great, I added this to https://github.com/log2timeline/dfvfs/wiki/Windows-Path-Resolver as yet another way paths are specified in Windows. Closing issue.

**Comment by hadar0x** [comment]
👍 

Saw you wrote "likely". Do you need a proof it corresponds to the volume serial number?

**Comment by joachimmetz** [comment]
likely here means that I've not verified it, and that I'm making a (hopefully) educated guess/assumption

If you can check then please do.

**Comment by hadar0x** [comment]
![capture](https://user-images.githubusercontent.com/12235915/48544713-e3587e00-e8cc-11e8-9b3c-bd164e90f403.PNG)

**Comment by joachimmetz** [comment]
thx for confirming
