### ISSUE TITLE
Improve format support: handle corrupted file

### ISSUE THREAD

**Issue by lfcnassif** [libyal/libagdb#3]
Running agdbinfo on the attached (corrupted?) file causes the program to hang for a long time and to leak hundreds of megabytes of memory.
[sample.zip](https://github.com/libyal/libagdb/files/2759532/sample.zip)

**Comment by joachimmetz** [comment]
thx for the report but as stated in the README this project is experimental and 
`Note that this project currently only focuses on the analysis of the format.`

I'll have a look when time permits

**Comment by lfcnassif** [comment]
Thank you for your attention, @joachimmetz

**Comment by joachimmetz** [comment]
Issue is due to corrupted test file. As I indicated (in the README and  in https://github.com/libyal/libagdb/issues/1) at this point in time this project aims on understanding the data format not on providing a production ready library.
